"""Adminship lives in the database

Admins used to come from `ADMIN_IDS` in the environment, or failing that from
`admins:` in app.yaml — read once at boot. There was no way to hand the bot to
somebody else, and no way to stop being an admin, without an SSH session.

This table lands **empty** and migrates no data. That is deliberate: the first
boot afterwards seeds it from `ADMIN_IDS` precisely because it is empty, so an
existing deployment keeps working with the environment it already has, and from
then on the database is the authority.

`uq_admin_single_owner` is a partial unique index — "exactly one OWNER" enforced
by SQLite rather than only by the use case, because two owners is not a state
anything here knows how to resolve. It matches `role = 'OWNER'` literally, so
`AdminRole.OWNER` must keep that value. Note this migration runs under
`render_as_batch`: any later batch operation that rebuilds `admin` has to
re-create the predicate by hand, or the rule is gone with no error.

Revision ID: 126795df8a8e
Revises: 84685f66a1f2
Create Date: 2026-09-12 15:40:33.974117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '126795df8a8e'
down_revision: Union[str, Sequence[str], None] = '84685f66a1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('telegram_user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', name='adminrole', native_enum=False, length=16), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=True),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_user_id')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_index('uq_admin_single_owner', ['role'], unique=True, sqlite_where=sa.text("role = 'OWNER'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index('uq_admin_single_owner', sqlite_where=sa.text("role = 'OWNER'"))

    op.drop_table('admin')
    # ### end Alembic commands ###
