"""Track scheduled posts and their pins

`bot_post` remembers the Tempo reminders and holiday greetings the bot has
posted. The pin is the reason: the previous Tempo reminder has to be unpinned
before the next is pinned, and the dict on the notifier that used to know which
one that was forgot it on every restart.

It is also a once-a-day guard. The delivery times moved into the `setting`
table, which needs no migration of its own, and moving a time after a job has
fired gives the same day a second occurrence the job ledger has never seen.

Revision ID: 47b7acff4a10
Revises: 90a9dcf65ba1
Create Date: 2026-09-16 17:59:07.328789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b7acff4a10'
down_revision: Union[str, Sequence[str], None] = '90a9dcf65ba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_post',
    sa.Column('office_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.Enum('TEMPO', 'HOLIDAY', name='postkind', native_enum=False, length=16), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('unpinned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['office_id'], ['office.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('office_id', 'kind', 'day')
    )
    with op.batch_alter_table('bot_post', schema=None) as batch_op:
        batch_op.create_index('ix_bot_post_chat', ['chat_id', 'kind', 'day'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_post', schema=None) as batch_op:
        batch_op.drop_index('ix_bot_post_chat')

    op.drop_table('bot_post')
    # ### end Alembic commands ###
