"""initial schema

Revision ID: 4ff0ae419a15
Revises:
Create Date: 2026-09-11 18:05:55.321091

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ff0ae419a15"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_usage",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("tokens", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", "day"),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index("ix_audit_at", ["at"], unique=False)

    op.create_table(
        "bot_mood",
        sa.Column("office_id", sa.String(length=64), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("mood", sa.String(length=16), nullable=False),
        sa.Column("chosen_by", sa.String(length=8), nullable=False),
        sa.PrimaryKeyConstraint("office_id", "day"),
    )
    op.create_table(
        "job_run",
        sa.Column("occurrence_key", sa.String(length=128), nullable=False),
        sa.Column("job", sa.String(length=64), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("late", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("occurrence_key"),
    )
    with op.batch_alter_table("job_run", schema=None) as batch_op:
        batch_op.create_index("ix_job_run_job_scheduled", ["job", "scheduled_for"], unique=False)

    op.create_table(
        "ledger_checkpoint",
        sa.Column("employee_id", sa.String(length=64), nullable=False),
        sa.Column("watermark", sa.Date(), nullable=False),
        sa.Column("days", sa.Integer(), nullable=False),
        sa.Column("entitlement_scaled", sa.Integer(), nullable=False),
        sa.Column("per_weekday", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("employee_id"),
    )
    op.create_table(
        "office",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("address", sa.String(length=256), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("holiday_calendar", sa.String(length=8), nullable=False),
        sa.Column("seed_nonce", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "calendar_exception",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("office_id", sa.String(length=64), nullable=True),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("note", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(["office_id"], ["office.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("office_id", "day", "kind", name="uq_calendar_exception"),
    )
    with op.batch_alter_table("calendar_exception", schema=None) as batch_op:
        batch_op.create_index("ix_calendar_exception_day", ["day"], unique=False)

    op.create_table(
        "employee",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("office_id", sa.String(length=64), nullable=False),
        sa.Column("full_name", sa.String(length=128), nullable=False),
        sa.Column("telegram_username", sa.String(length=32), nullable=True),
        sa.Column("telegram_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "gender",
            sa.Enum("male", "female", name="gender", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("team_id", sa.String(length=64), nullable=True),
        sa.Column("started_on", sa.Date(), nullable=True),
        sa.Column("ended_on", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(["office_id"], ["office.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_user_id"),
    )
    with op.batch_alter_table("employee", schema=None) as batch_op:
        batch_op.create_index("ix_employee_office", ["office_id"], unique=False)

    op.create_table(
        "generation_run",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("office_id", sa.String(length=64), nullable=False),
        sa.Column("horizon_start", sa.Date(), nullable=False),
        sa.Column("horizon_end", sa.Date(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("solver_version", sa.String(length=16), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("objective", sa.String(length=128), nullable=False),
        sa.Column("added", sa.Integer(), nullable=False),
        sa.Column("removed", sa.Integer(), nullable=False),
        sa.Column("kept", sa.Integer(), nullable=False),
        sa.Column("shortfall", sa.Integer(), nullable=False),
        sa.Column("triggered_by", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["office_id"], ["office.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "schedule_day",
        sa.Column("office_id", sa.String(length=64), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("is_workday", sa.Boolean(), nullable=False),
        sa.Column("desks_required", sa.Integer(), nullable=False),
        sa.Column("available_count", sa.Integer(), nullable=False),
        sa.Column("available_ids", sa.JSON(), nullable=False),
        sa.Column("entitlement_scaled", sa.Integer(), nullable=False),
        sa.Column("filled", sa.Integer(), nullable=False),
        sa.Column("shortfall", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("announced_at", sa.DateTime(), nullable=True),
        sa.Column("roster_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("generation_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["office_id"], ["office.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("office_id", "day"),
    )
    with op.batch_alter_table("schedule_day", schema=None) as batch_op:
        batch_op.create_index("ix_schedule_day_day", ["day"], unique=False)

    op.create_table(
        "weekly_template",
        sa.Column("office_id", sa.String(length=64), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("vacant_desks", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["office_id"], ["office.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("office_id", "weekday"),
    )
    op.create_table(
        "absence",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("employee_id", sa.String(length=64), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "vacation",
                "sick",
                "trip",
                "other",
                name="absencekind",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=256), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["employee_id"], ["employee.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("absence", schema=None) as batch_op:
        batch_op.create_index(
            "ix_absence_employee_range", ["employee_id", "start_date", "end_date"], unique=False
        )

    op.create_table(
        "assignment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("office_id", sa.String(length=64), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("employee_id", sa.String(length=64), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "fixed", "drafted", "manual", name="assignmentsource", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "provisional",
                "announced",
                "cancelled",
                name="assignmentstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("generation_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("announced_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_reason", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(["employee_id"], ["employee.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["office_id"], ["office.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("assignment", schema=None) as batch_op:
        batch_op.create_index("ix_assignment_employee_day", ["employee_id", "day"], unique=False)
        batch_op.create_index("ix_assignment_office_day", ["office_id", "day"], unique=False)

    op.create_table(
        "attendance_ledger",
        sa.Column("employee_id", sa.String(length=64), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("days", sa.Integer(), nullable=False),
        sa.Column("entitlement_scaled", sa.Integer(), nullable=False),
        sa.Column("surplus_scaled", sa.Integer(), nullable=False),
        sa.Column("per_weekday", sa.String(length=64), nullable=False),
        sa.Column("rebuilt_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["employee_id"], ["employee.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("employee_id"),
    )
    op.create_table(
        "template_fixed",
        sa.Column("office_id", sa.String(length=64), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["employee_id"], ["employee.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["office_id"], ["office.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("office_id", "weekday", "employee_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("template_fixed")
    op.drop_table("attendance_ledger")
    with op.batch_alter_table("assignment", schema=None) as batch_op:
        batch_op.drop_index("ix_assignment_office_day")
        batch_op.drop_index("ix_assignment_employee_day")

    op.drop_table("assignment")
    with op.batch_alter_table("absence", schema=None) as batch_op:
        batch_op.drop_index("ix_absence_employee_range")

    op.drop_table("absence")
    op.drop_table("weekly_template")
    with op.batch_alter_table("schedule_day", schema=None) as batch_op:
        batch_op.drop_index("ix_schedule_day_day")

    op.drop_table("schedule_day")
    op.drop_table("generation_run")
    with op.batch_alter_table("employee", schema=None) as batch_op:
        batch_op.drop_index("ix_employee_office")

    op.drop_table("employee")
    with op.batch_alter_table("calendar_exception", schema=None) as batch_op:
        batch_op.drop_index("ix_calendar_exception_day")

    op.drop_table("calendar_exception")
    op.drop_table("office")
    op.drop_table("ledger_checkpoint")
    with op.batch_alter_table("job_run", schema=None) as batch_op:
        batch_op.drop_index("ix_job_run_job_scheduled")

    op.drop_table("job_run")
    op.drop_table("bot_mood")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_at")

    op.drop_table("audit_log")
    op.drop_table("ai_usage")
    # ### end Alembic commands ###
