"""Chat message cache and bot memory

Two tables behind the chat's conversation context.

`chat_message` is a short-lived cache of what the bot has seen. Telegram populates
`reply_to_message` exactly one level deep, so following a thread any further back means
having kept the messages ourselves. Rows are pruned after a few days — nobody follows a
thread back a fortnight.

`chat_memory` holds the short facts the model asked to keep, in two scopes: `office`
(shared) and `employee` (shown only to the person it is about). Both are ring buffers
bounded by config rather than by time, so the prompt built from them has a fixed maximum
size. `chat_id` is a plain Integer, as `office.chat_id` already is: SQLite's INTEGER is
64-bit, which a supergroup id needs.

Revision ID: 84685f66a1f2
Revises: 4ff0ae419a15
Create Date: 2026-09-12 01:48:59.700637

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "84685f66a1f2"
down_revision: Union[str, Sequence[str], None] = "4ff0ae419a15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_memory",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("subject", sa.String(length=64), nullable=False),
        sa.Column("fact", sa.Text(), nullable=False),
        sa.Column("at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chat_memory", schema=None) as batch_op:
        batch_op.create_index(
            "ix_chat_memory_scope_subject", ["scope", "subject", "id"], unique=False
        )

    op.create_table(
        "chat_message",
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("author", sa.String(length=128), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("reply_to_message_id", sa.Integer(), nullable=True),
        sa.Column("at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("chat_id", "message_id"),
    )
    with op.batch_alter_table("chat_message", schema=None) as batch_op:
        batch_op.create_index("ix_chat_message_at", ["at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_message", schema=None) as batch_op:
        batch_op.drop_index("ix_chat_message_at")

    op.drop_table("chat_message")
    with op.batch_alter_table("chat_memory", schema=None) as batch_op:
        batch_op.drop_index("ix_chat_memory_scope_subject")

    op.drop_table("chat_memory")
    # ### end Alembic commands ###
