"""Per-employee AI limits

The daily AI allowance was already per person — `ai_usage` is keyed on
(user_id, day) — but it was the same number for everybody and could only be
changed by editing app.yaml and deploying.

`employee.ai_daily_limit` is NULL for everyone, meaning "the configured
default". That is the point of the nullable column rather than a backfill:
raising the default later lifts everybody who was never singled out, and only
the people an admin has deliberately moved stay where they are.

`setting` holds the default itself, and the global cost cap, as overrides of
app.yaml. A missing row means the file wins, so nothing needs migrating when a
default changes in a release.

Revision ID: 90a9dcf65ba1
Revises: 126795df8a8e
Create Date: 2026-09-12 19:07:01.459015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a9dcf65ba1'
down_revision: Union[str, Sequence[str], None] = '126795df8a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_daily_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('ai_daily_limit')

    op.drop_table('setting')
    # ### end Alembic commands ###
